Add app library and dagger test dependency.

diff --git a/buckw b/buckw
--- a/buckw
+++ b/buckw
@@ -4,7 +4,7 @@
 ##
 ##  Buck wrapper script to invoke okbuck when needed, before running buck
 ##
-##  Created by OkBuck Gradle Plugin on : Fri Nov 18 11:30:35 PST 2016
+##  Created by OkBuck Gradle Plugin on : Tue Jan 31 12:03:19 PST 2017
 ##
 #########################################################################
 
@@ -62,19 +62,22 @@ ensureWatch ( ) {
     watchman watch-project $WORKING_DIR >/dev/null 2>&1
 }
 
+removeWatch ( ) {
+    watchman watch-del $WORKING_DIR >/dev/null 2>&1
+}
+
 getToClean ( ) {
     ensureWatch
 
-    watchman --output-encoding=json -j 2>&1 <<-EOT
+    watchman --output-encoding=json --no-pretty -j 2>&1 <<-EOT
 ["query", "$WORKING_DIR", {
     "expression": ["allof",
         ["type", "f"],
         ["anyof",
-            ["imatch", ".buckconfig.local", "wholename"],
-            ["imatch", "**/BUCK", "wholename"]
+            ["name", ["BUCK", ".buckconfig.local"]]
         ],
         ["not",
-            ["imatch", ".okbuck/**/BUCK", "wholename"]
+            ["dirname", ".okbuck"]
         ]
     ],
     "fields": ["name"]
@@ -85,30 +88,29 @@ EOT
 getChanges ( ) {
     ensureWatch
 
-    WATCHED_CHANGES=`watchman --output-encoding=json -j 2>&1 <<-EOT
+    WATCHED_CHANGES=`watchman --output-encoding=json --no-pretty -j 2>&1 <<-EOT
 ["query", "$WORKING_DIR", {
     "since": "n:okbuck_trig",
     "expression": ["allof",
         ["type", "f"],
         ["anyof",
-            ["imatch", "**/*.gradle", "wholename"],
-            ["imatch", "**/src/**/AndroidManifest.xml", "wholename"],
-            ["imatch", "**/gradle-wrapper.properties", "wholename"],
-            ["imatch", "**/lint.xml", "wholename"]
+            ["suffix", "gradle"],
+            ["name", ["gradle-wrapper.properties", "lint.xml"]],
+            ["match", "**/src/**/AndroidManifest.xml", "wholename"]
         ]
     ],
     "fields": ["name"]
 }]
 EOT`
-    SOURCE_ROOTS=`watchman --output-encoding=json -j 2>&1 <<-EOT
+    SOURCE_ROOTS=`watchman --output-encoding=json --no-pretty -j 2>&1 <<-EOT
 ["query", ".", {
     "since": "n:okbuck_source_roots",
     "expression": ["allof",
         ["type", "d"],
         ["anyof",
-            ["imatch", "**/src/**/java", "wholename"],
-            ["imatch", "**/src/**/res", "wholename"],
-            ["imatch", "**/src/**/resources", "wholename"]
+            ["match", "**/src/**/java", "wholename"],
+            ["match", "**/src/**/res", "wholename"],
+            ["match", "**/src/**/resources", "wholename"]
         ]
     ],
     "fields": ["new", "exists", "name"]
@@ -127,13 +129,19 @@ runOkBuck ( ) {
     echo
 
     if [[ ! -z "$INSTALLED_WATCHMAN" ]]; then
-        getToClean | jsonq '"\n".join(obj["files"])' | xargs rm
-        info "DELETED OLD BUCK FILES"
-        EXTRA_OKBUCK_ARGS="-xokbuckClean $EXTRA_OKBUCK_ARGS"
+        TO_CLEAN=$(getToClean | jsonq '"\n".join(obj["files"])')
+        if [[ $? -eq 0 ]]; then
+            echo $TO_CLEAN | xargs rm
+            info "DELETED OLD BUCK FILES"
+            EXTRA_OKBUCK_ARGS="-xokbuckClean $EXTRA_OKBUCK_ARGS"
+        else
+            warn "WATCHMAN FAILED. USING OKBUCKCLEAN."
+            removeWatch
+        fi
     fi
 
     rm -f $OKBUCK_SUCCESS
-    ( $WORKING_DIR/gradlew -p $WORKING_DIR okbuck -Dokbuck.wrapper=true $EXTRA_OKBUCK_ARGS --stacktrace &&
+    ( $WORKING_DIR/gradlew -p $WORKING_DIR okbuck -Dokbuck.wrapper=true $EXTRA_OKBUCK_ARGS &&
     updateOkBuckSuccess && success "PROCEEDING WITH BUCK" ) || die "OKBUCK FAILED"
 }
 
